#ifndef HG_CHONPS_MOUSE_BUTTON_CODES_H
#define HG_CHONPS_MOUSE_BUTTON_CODES_H


// From glfw3.h
#define CHONPS_MOUSE_BUTTON_1         0
#define CHONPS_MOUSE_BUTTON_2         1
#define CHONPS_MOUSE_BUTTON_3         2
#define CHONPS_MOUSE_BUTTON_4         3
#define CHONPS_MOUSE_BUTTON_5         4
#define CHONPS_MOUSE_BUTTON_6         5
#define CHONPS_MOUSE_BUTTON_7         6
#define CHONPS_MOUSE_BUTTON_8         7
#define CHONPS_MOUSE_BUTTON_LAST      CHONPS_MOUSE_BUTTON_8
#define CHONPS_MOUSE_BUTTON_LEFT      CHONPS_MOUSE_BUTTON_1
#define CHONPS_MOUSE_BUTTON_RIGHT     CHONPS_MOUSE_BUTTON_2
#define CHONPS_MOUSE_BUTTON_MIDDLE    CHONPS_MOUSE_BUTTON_3

#define CHONPS_ARROW_CURSOR   0x00036001
#define CHONPS_IBEAM_CURSOR   0x00036002
#define CHONPS_CROSSHAIR_CURSOR   0x00036003
#define CHONPS_POINTING_HAND_CURSOR   0x00036004
#define CHONPS_RESIZE_EW_CURSOR   0x00036005
#define CHONPS_RESIZE_NS_CURSOR   0x00036006
#define CHONPS_RESIZE_NWSE_CURSOR   0x00036007
#define CHONPS_RESIZE_NESW_CURSOR   0x00036008
#define CHONPS_RESIZE_ALL_CURSOR   0x00036009
#define CHONPS_NOT_ALLOWED_CURSOR   0x0003600A


#endif