#ifndef MOUSE_BUTTON_CODES_H
#define MOUSE_BUTTON_CODES_H


// From glfw3.h
#define CHONPS_MOUSE_BUTTON_1         0
#define CHONPS_MOUSE_BUTTON_2         1
#define CHONPS_MOUSE_BUTTON_3         2
#define CHONPS_MOUSE_BUTTON_4         3
#define CHONPS_MOUSE_BUTTON_5         4
#define CHONPS_MOUSE_BUTTON_6         5
#define CHONPS_MOUSE_BUTTON_7         6
#define CHONPS_MOUSE_BUTTON_8         7
#define CHONPS_MOUSE_BUTTON_LAST      CHONPS_MOUSE_BUTTON_8
#define CHONPS_MOUSE_BUTTON_LEFT      CHONPS_MOUSE_BUTTON_1
#define CHONPS_MOUSE_BUTTON_RIGHT     CHONPS_MOUSE_BUTTON_2
#define CHONPS_MOUSE_BUTTON_MIDDLE    CHONPS_MOUSE_BUTTON_3


#endif